# Generated by Django 2.2.2 on 2020-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loopback', models.CharField(max_length=128, unique=True, verbose_name='LoopBack')),
                ('hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('ip', models.GenericIPAddressField()),
                ('title', models.CharField(choices=[('ag1', 'AG1'), ('css', 'CSS')], default='ag1', max_length=20)),
            ],
        ),
    ]
