# Generated by Django 2.2.2 on 2020-09-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='title',
            new_name='type',
        ),
    ]
