# Generated by Django 2.2.16 on 2020-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('loopback', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
